/**
 * Grand Prize
 * The ultimate jackpot prize
 * 
 * Generated by Prize Designer
 */

import type { Prize } from '../../mechanics/prizes';

export const GRAND_PRIZE: Prize = {
  name: 'Grand Prize',
  value: '$1000',
  emoji: '🏆',
};
