/**
 * No Prize
 * $0
 * 
 * Generated by Prize Designer
 * Date: 2025-11-29T15:50:48.966Z
 * 
 * To use this prize:
 * 1. Save this file to: core/game-logic/prizes/no-prize.ts
 * 2. Import in core/mechanics/prizes.ts:
 *    import { NO_PRIZE_PRIZE } from '../game-logic/prizes/no-prize';
 * 3. Add to prizes array or use directly in game logic
 */

import type { Prize } from '../../mechanics/prizes';

export const NO_PRIZE_PRIZE: Prize = {
  "id": "no-prize",
  "name": "No Prize",
  "value": "$0",
  "emoji": "🚫",
};
