/**
 * Goblin Gold
 * Fantasy-themed ticket with 10 scratch areas - match three symbols to win
 * 
 * Generated by Ticket Layout Designer
 * Date: 2025-11-29T16:07:25.884Z
 * 
 * To use this layout:
 * 1. Save this file to: core/game-logic/tickets/goblin-goldLayout.ts
 * 2. Import in core/mechanics/ticketLayouts.ts:
 *    import { GOBLIN_GOLD_TICKET } from '../game-logic/tickets/goblin-goldLayout';
 * 3. Add to TICKET_LAYOUTS object:
 *    'goblin-gold': GOBLIN_GOLD_TICKET,
 */

import type { TicketLayout } from '../../../mechanics/ticketLayouts';
import imageAsset from './basic-goblinGold-ticketAsset.png';

export const GOBLIN_GOLD_TICKET: TicketLayout = {
  "id": "goblin-gold",
  "name": "Goblin Gold",
  "description": "Fantasy-themed ticket with 10 scratch areas - match three symbols to win",
  "backgroundImage": imageAsset,
  "scratchAreas": [
    {
      "id": "area-1",
      "topPercent": 0.6018822594026548,
      "leftPercent": 0.0802980132450331,
      "widthPercent": 0.13576158940397348,
      "heightPercent": 0.08849557522123898,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-2",
      "topPercent": 0.5985636753318584,
      "leftPercent": 0.25579470198675497,
      "widthPercent": 0.14238410596026488,
      "heightPercent": 0.0951327433628319,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-3",
      "topPercent": 0.5996698700221239,
      "leftPercent": 0.4296357615894039,
      "widthPercent": 0.14403973509933782,
      "heightPercent": 0.0951327433628319,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-4",
      "topPercent": 0.6007760647123894,
      "leftPercent": 0.6084437086092715,
      "widthPercent": 0.13907284768211914,
      "heightPercent": 0.0940265486725664,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-5",
      "topPercent": 0.6007760647123894,
      "leftPercent": 0.7806291390728477,
      "widthPercent": 0.14569536423841054,
      "heightPercent": 0.0951327433628319,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-6",
      "topPercent": 0.7169265071902655,
      "leftPercent": 0.0802980132450331,
      "widthPercent": 0.13576158940397348,
      "heightPercent": 0.0951327433628319,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-7",
      "topPercent": 0.7180327018805309,
      "leftPercent": 0.2574503311258278,
      "widthPercent": 0.13741721854304634,
      "heightPercent": 0.09292035398230092,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-8",
      "topPercent": 0.7158203125,
      "leftPercent": 0.43129139072847683,
      "widthPercent": 0.13907284768211922,
      "heightPercent": 0.0951327433628319,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-9",
      "topPercent": 0.7180327018805309,
      "leftPercent": 0.6051324503311258,
      "widthPercent": 0.14238410596026482,
      "heightPercent": 0.0940265486725664,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    },
    {
      "id": "area-10",
      "topPercent": 0.7180327018805309,
      "leftPercent": 0.7806291390728477,
      "widthPercent": 0.14238410596026493,
      "heightPercent": 0.09070796460176994,
      "canvasWidth": 100,
      "canvasHeight": 100,
      "revealThreshold": 50
    }
  ],
  "revealMechanic": "independent",
  "winCondition": "match-three",
  "ticketWidth": 1024,
  "ticketHeight": 1536,
  "goldCost": 15,
  "prizeConfigs": [
    {
      "prizeId": "grand-prize",
      "weight": 1
    },
    {
      "prizeId": "crown",
      "weight": 3
    },
    {
      "prizeId": "diamond",
      "weight": 4
    },
    {
      "prizeId": "no-prize",
      "weight": 10
    }
  ]
};
