/**
 * Test layout generated by the Layout Designer tool
 * This layout has two vertical columns with match-two win condition.
 */

import type { TicketLayout } from '../../mechanics/ticketLayouts';

export const TEST_TWO_COLUMN_TICKET: TicketLayout = {
  id: 'test-two-column',
  name: 'Test Two Column Ticket',
  description: 'A test ticket with two vertical scratch areas - match two to win',
  goldCost: 5,
  scratchAreas: [
    {
      id: 'left-column',
      topPercent: 0.1,
      leftPercent: 0.05,
      widthPercent: 0.4,
      heightPercent: 0.8,
      canvasWidth: 200,
      canvasHeight: 240,
      revealThreshold: 50,
    },
    {
      id: 'right-column',
      topPercent: 0.1,
      leftPercent: 0.55,
      widthPercent: 0.4,
      heightPercent: 0.8,
      canvasWidth: 200,
      canvasHeight: 240,
      revealThreshold: 50,
    },
  ],
  revealMechanic: 'independent',
  winCondition: 'match-two',
  ticketWidth: 500,
  ticketHeight: 300,
  // Test ticket with standard prize pool
  prizeConfigs: [
    { prizeId: 'diamond', weight: 5 },
    { prizeId: 'magic-potion', weight: 8 },
    { prizeId: 'lucky-star', weight: 5 },
    { prizeId: 'shield', weight: 10 },
  ],
};
