/**
 * Test layout generated by the Layout Designer tool
 * This layout has two vertical columns
 */

import type { TicketLayout } from '../../mechanics/ticketLayouts';

export const TEST_TWO_COLUMN_TICKET: TicketLayout = {
  id: 'test-two-column',
  name: 'Test Two Column Ticket',
  description: 'A test ticket with two vertical scratch areas',
  scratchAreas: [
    {
      id: 'left-column',
      topPercent: 0.1,
      leftPercent: 0.05,
      widthPercent: 0.4,
      heightPercent: 0.8,
      canvasWidth: 200,
      canvasHeight: 240,
      revealThreshold: 50,
    },
    {
      id: 'right-column',
      topPercent: 0.1,
      leftPercent: 0.55,
      widthPercent: 0.4,
      heightPercent: 0.8,
      canvasWidth: 200,
      canvasHeight: 240,
      revealThreshold: 50,
    },
  ],
  revealMechanic: 'reveal-all',
  winCondition: 'reveal-all-areas',
  ticketWidth: 500,
  ticketHeight: 300,
};
