/**
 * Gold Coin Scratcher
 * Classic coin scratcher - medium scratch area
 * 
 * Generated by Scratcher Designer
 */

import type { Scratcher } from '../../mechanics/scratchers';

export const GOLD_COIN_SCRATCHER: Scratcher = {
  id: 'gold-coin',
  name: 'Gold Coin',
  description: 'Classic coin scratcher - medium scratch area',
  symbol: '🪙',
  scratchRadius: 25,
  style: {
    overlayColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    overlayPattern: 'SCRATCH',
  },
};
